### ISSUE TITLE
Feature: Debug symbols package and sourcelink

### ISSUE THREAD

**Issue by sommmen** [StringEpsilon/PhpSerializerNET#19]
Hello,

I'd love being able to debug the library on the fly in my app and the process seems simple enough.

https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg
https://github.com/dotnet/sourcelink/blob/main/README.md

The commandline option seems to work fine to generate a symbols package.

```
PM> cd PhpSerializerNET
PM> dotnet pack PhpSerializerNET.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  PhpSerializerNET -> C:\Repos\PhpSerializerNET\PhpSerializerNET\bin\Debug\net6.0\PhpSerializerNET.dll
  Successfully created package 'C:\Repos\PhpSerializerNET\PhpSerializerNET\bin\Debug\PhpSerializerNET.0.9.0.nupkg'.
  Successfully created package 'C:\Repos\PhpSerializerNET\PhpSerializerNET\bin\Debug\PhpSerializerNET.0.9.0.snupkg'.
```

Seems like you can also embed the dbg symbols which would be easier, but that would bump the package size a bit, hence why a seperate symbols package is recommended.

> Note that symbol package isn't the only strategy to make the debug symbols available to the consumers of your library. It's also possible to embed them in the dll or exe with the following project property: <DebugType>embedded</DebugType>

**Comment by StringEpsilon** [comment]
I do build and publish the symbol package already and have for a while now:

https://www.nuget.org/api/v2/symbolpackage/PhpSerializerNET/0.9.0

**Comment by sommmen** [comment]
> I do build and publish the symbol package already and have for a while now:
> 
> https://www.nuget.org/api/v2/symbolpackage/PhpSerializerNET/0.9.0

Hm weird vs is not picking it up for some reason.. I'll investigate.
