### ISSUE TITLE
unrecognized token

### ISSUE THREAD

**Issue by sommmen** [StringEpsilon/PhpSerializerNET#3]
Hiya,

I just ran into the following issue and i was wondering if you could help me:

Input string:
``` 
a:1:{i:0;O:31:"KPS\Logistics\Status\To\Regular":3:{s:4:"from";s:8:"produced";s:2:"to";s:8:"produced";s:4:"date";O:8:"DateTime":3:{s:4:"date";s:26:"2021-08-18 09:10:23.441055";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}}}
```

Which gave me the following exception:
> PhpSerializerNET.DeserializationException: 'Unexpected token 'O' at position 9.'

``` csharp
                        var statusLogString = items.First().statusLogString;
                        var deserialized = PhpSerializer.Deserialize(statusLogString, new PhpDeserializationOptions()
                        {
                            CaseSensitiveProperties = false
                        });
```

**Comment by sommmen** [comment]
https://www.functions-online.com/unserialize.html

Shows:

``` 
error:
FATAL: invalid class name KPS\Logistics\Status\To\Regular
``` 

``` 
array (
  0 => 
  __PHP_Incomplete_Class::__set_state(array(
     '__PHP_Incomplete_Class_Name' => 'KPS\Logistics\Status\To\Regular',
     'from' => 'produced',
     'to' => 'produced',
     'date' => 
    DateTime::__set_state(array(
       'date' => '2021-08-18 09:10:23.441055',
       'timezone_type' => 3,
       'timezone' => 'UTC',
    )),
  )),
)
```

I'm not familiar with PHP what could this mean?

**Comment by sommmen** [comment]
I'm coming to the realization that perhaps deserializing Php objects is not supported yet.
Perhaps make a better error message, like `if(token == 'o') throw notsupportedexception()` you get the jist. 

Is object deserialization support planned for you or not at all?

**Comment by StringEpsilon** [comment]
Hi,

Object support is  fully implemented, I just hadn't wrapped a new release for it yet. It should be pretty comprehensive support, I just hadn't had the time and inspiration to write the documentation for it, so I didn't release it.

If you need the support right now, I can bundle something up. Just beware that 0.5.0 will have some minor breaking changes.

**Comment by StringEpsilon** [comment]
I released https://github.com/StringEpsilon/PhpSerializerNET/releases/tag/0.5.0 

That should fix this issue. I will open a new issue for the missing documentation.

**Comment by sommmen** [comment]
@StringEpsilon  hiya! thanks for pushing out a quick update.

I seem to be getting stuck again however. Consider the following string:

``` 
a:1:{i:0;O:31:"KPS\Logistics\Status\To\Regular":3:{s:4:"from";s:8:"produced";s:2:"to";s:8:"produced";s:4:"date";O:8:"DateTime":3:{s:4:"date";s:26:"2021-08-18 09:10:23.441055";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}}}
````

``` csharp 
var deserialized = PhpSerialization.Deserialize(logString);
``` 

Gives the exception:
`Malformed array at position 9`

**Comment by StringEpsilon** [comment]
Multiple small bugs colluding on this. 
First I copy and pasted the error message for that exception wrong (the object is "malformed"). Then the regex for checking if the object syntax is correct was too strict. There is also an issue with the way the deserializer decides to go for a dictionary/dynamic vs. a specified type (by the class).

All small stuff. Except that the `DateTime`  object will also refuse to deserialize unless you set the option `EnableTypeLookup` to false. I will have to give that one a think with more coffee. But I'll push the other stuff as 0.5.1. soon.

**Comment by sommmen** [comment]
@StringEpsilon Disabling TypeLookup seems to work as far as i can see.

I've got to go through about a 500.000 lines so i'll run this for a bit and if i see anything weird come up.

**Comment by sommmen** [comment]
Also something i'm missing, when i have an object (and im using 'EnableTypeLookup' == false here ) it gets serialized into a dictionary - this is fine, however in that case i lose the classname - which i need to make sense of the object.

Would it be possible to add a key '__PHP_OBJECT_CLASSNAME' with the classname for an object?
Or perhaps you could do something like this:

``` csharp
class PhpSerializedObjectDictionary : Dictionary<string, object>
{
        public string PhpObjectName { get; set; }
}
```

**Comment by StringEpsilon** [comment]
Can you open follow-up as separate issues? It's becoming hard to keep track of all this if you just gonna comment on this one :)

**Comment by sommmen** [comment]
> Can you open follow-up as separate issues? It's becoming hard to keep track of all this if you just gonna comment on this one :)

Certainly - apologies i did not want to clutter the issue board. I'll repost.
