### ISSUE TITLE
Add support for object/class names

### ISSUE THREAD

**Issue by sommmen** [StringEpsilon/PhpSerializerNET#5]
Also something i'm missing, when i have an object (and im using 'EnableTypeLookup' == false here ) it gets serialized into a dictionary - this is fine, however in that case i lose the classname - which i need to make sense of the object.

Would it be possible to add a key '__PHP_OBJECT_CLASSNAME' with the classname for an object?
Or perhaps you could do something like this:

``` csharp
class PhpSerializedObjectDictionary : Dictionary<string, object>
{
        public string PhpObjectName { get; set; }
}
```

**Comment by StringEpsilon** [comment]
If you build the entire object structure, you can use `PhpSerialization.Deserialize<T>()` too. That sidesteps the type lookup too.

But I agree that having the class name on the dictionary / ExpandoObject would be helpful.

**Comment by sommmen** [comment]
> If you build the entire object structure, you can use `PhpSerialization.Deserialize<T>()` too. That sidesteps the type lookup too.
> 
> But I agree that having the class name on the dictionary / ExpandoObject would be helpful.

Certainly - the problem is that i have different object types in a single array.
So i need to know which object is which in order for me to get a correct list.

for example:
`a:2:{i:0;O:31:"KPS\Logistics\Status\To\Delayed":5:{s:12:"delay_reason";s:12:"out_of_stock";s:11:"delay_until";O:8:"DateTime":3:{s:4:"date";s:26:"2021-08-26 00:00:00.000000";s:13:"timezone_type";i:1;s:8:"timezone";s:6:"+00:00";}s:4:"from";s:7:"delayed";s:2:"to";s:7:"delayed";s:4:"date";O:8:"DateTime":3:{s:4:"date";s:26:"2021-08-16 15:04:10.429836";s:13:"timezone_type";i:3;s:8:"timezone";s:16:"Europe/Amsterdam";}}i:1;O:31:"KPS\Logistics\Status\To\Regular":3:{s:4:"from";s:10:"processing";s:2:"to";s:10:"processing";s:4:"date";O:8:"DateTime":3:{s:4:"date";s:26:"2021-08-18 06:37:19.626840";s:13:"timezone_type";i:3;s:8:"timezone";s:3:"UTC";}}}
` 

Holds `KPS\Logistics\Status\To\Delayed` and `O:31:"KPS\Logistics\Status\To\Regular` which have common properties ( i assume they'd inherit from eachother or what not) but also properties not common.

In that case i'd need to know the classname so i can branch accordingly.

**Comment by StringEpsilon** [comment]
I decided to keep it a little more generic. You can review the changes here:

535165b79e3fa50801617befffcd5d707f2fcc20 

Basically, you can  de-serialize your objects into PhpObjectDictionary, which implements IPhpObject. Any IPhpObject will automatically get the class name set and will provide that via `GetClassName()`. Same goes for serialization as well: `GetClassName()` will be used to determine the class name for the output.

Is that something you can work with?

**Comment by sommmen** [comment]
Seems fine! perfect actually. I'll look forward to the update.

It does seem a bit weird have an IPhpObject with a public setter for the property.

Just a recommendation but, Perhaps make the setter not public (or implement an internal interface for your own use).
Or heck - pass it into the ctor and make it readonly... but that depends on other requirements ofcourse.

**Comment by StringEpsilon** [comment]
The idea behind the setter being public is to allow folks to be more flexible with serialization at runtime.

**Comment by StringEpsilon** [comment]
0.6.0. is released and should be on nuget.org shortly.
